#!/bin/bash --login
#SBATCH --job-name=7_bases
#SBATCH --output=out/groebner_n_%a.out
#SBATCH --time=168:00:00  
#SBATCH --mem=1000G
#SBATCH --mail-user=wack@math.tu-berlin.de
#SBATCH --mail-type=BEGIN,END,FAIL


export JULIA_NUM_PRECOMPILE_TASKS=1
unset LD_LIBRARY_PATH 
JULIA_DEPOT_PATH=$TMPDIR/julia julia-1.9 -e "using Pkg; Pkg.activate(\"../\",io=devnull); Pkg.instantiate(io=devnull); include(\"./cluster_job.jl\"); "
